# Generated by Django 5.2.8 on 2025-11-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0008_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
