# Generated by Django 5.2.8 on 2025-11-28 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=4)),
                ('dev', models.BooleanField(default=False)),
                ('des', models.BooleanField(default=False)),
                ('pm', models.BooleanField(default=False)),
                ('core', models.BooleanField(default=False)),
                ('mentor', models.BooleanField(default=False)),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(blank=True, max_length=100)),
                ('birthday', models.CharField(help_text='MM-DD format', max_length=5)),
                ('home', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('favorite_thing_1', models.CharField(max_length=100)),
                ('favorite_thing_2', models.CharField(max_length=100)),
                ('favorite_thing_3', models.CharField(max_length=100)),
                ('favorite_dartmouth_tradition', models.CharField(max_length=100)),
                ('fun_fact', models.TextField()),
                ('picture', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
