# Generated by Django 5.2.8 on 2025-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='favorite_dartmouth_tradition',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='favorite_thing_1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='favorite_thing_2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='favorite_thing_3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fun_fact',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='home',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='minor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='quote',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('GR', 'Graduate')], default='2024', max_length=4),
        ),
    ]
